/* global __dirname */
const assert = require('node:assert/strict'), crypto = require('node:crypto'), fs = require('node:fs'), path = require('node:path'), vm = require('node:vm'), ts = require('typescript');
const files = new Map(), dirs = new Set(['document:', 'cache:']);
class Directory { constructor(base, ...parts) { this.uri = [base.uri || base, ...parts].join('/'); } get exists(){return dirs.has(this.uri)} create(){dirs.add(this.uri)} delete(){ for(const key of [...files.keys()]) if(key.startsWith(this.uri+'/')) files.delete(key); for(const key of [...dirs]) if(key===this.uri||key.startsWith(this.uri+'/')) dirs.delete(key) } list(){ const prefix=this.uri+'/'; const names=new Set([...dirs,...files.keys()].filter(x=>x.startsWith(prefix)&&!x.slice(prefix.length).includes('/')).map(x=>x.slice(prefix.length))); return [...names].map(n=>dirs.has(prefix+n)?new Directory(this,n):new File(this,n)); } }
class File { constructor(base,...parts){this.uri=[base.uri||base,...parts].join('/')} get name(){return this.uri.split('/').pop()} get exists(){return files.has(this.uri)} get size(){return files.get(this.uri)?.length||0} create(){files.set(this.uri,new Uint8Array())} write(v){files.set(this.uri,typeof v==='string'?new TextEncoder().encode(v):new Uint8Array(v))} async bytes(){if(!this.exists)throw Error('missing');return files.get(this.uri)} async text(){return new TextDecoder().decode(await this.bytes())} async copy(dest){dest.write(await this.bytes())} delete(){files.delete(this.uri)} }
const mocks={ 'expo-file-system':{Directory,File,Paths:{document:{uri:'document:'},cache:{uri:'cache:'}}}, 'expo-constants':{default:{expoConfig:{version:'1.0.0'},nativeBuildVersion:'9'}}, 'expo-crypto':{CryptoDigestAlgorithm:{SHA256:'SHA-256'},digest:async(_a,b)=>{const h=crypto.createHash('sha256').update(Buffer.from(b)).digest();return h.buffer.slice(h.byteOffset,h.byteOffset+h.byteLength)}} };
function load(rel){const exports={};const code=ts.transpileModule(fs.readFileSync(path.join(__dirname,'..',rel),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText;vm.runInNewContext(code,{exports,require:(name)=>name in mocks?mocks[name]:load(`${name.startsWith('@/')?'src/'+name.slice(2):path.join(path.dirname(rel),name)}.ts`),TextEncoder,TextDecoder,Uint8Array,Date,JSON,Set,Object,Error});return exports}
async function main(){
 const format=load('src/features/backup/backup-format.ts'), service=load('src/features/backup/backup-service.ts');
 assert.throws(()=>format.assertSafeBackupPath('../escape')); assert.throws(()=>format.assertSafeBackupPath('/absolute'));
 dirs.add('document:/vehicle-photos'); dirs.add('document:/vehicle-photos/1'); files.set('document:/vehicle-photos/1/photo.jpg',Uint8Array.from([4,5,6]));
 const source=Uint8Array.from([1,2,3]); const db={serializeAsync:async()=>source,getFirstAsync:async()=>({user_version:9})};
 const before=source.slice(); const result=await service.createBackup(db,{now:new Date('2026-09-21T00:00:00.000Z')});
 assert.equal(result.manifest.format,format.BACKUP_FORMAT); assert.equal(result.manifest.formatVersion,1); assert.equal(result.manifest.database.schemaVersion,9); assert.equal(result.manifest.persistentFileCount,1); assert.equal(result.manifest.entries.length,2); assert.ok(result.manifest.entries.every(e=>/^[a-f0-9]{64}$/.test(e.sha256))); assert.deepEqual([...source],[...before]);
 await service.verifyBackup(result.file); assert.equal(new Directory('cache:','lifepilot-backup-staging').exists,false);
 const pkg=JSON.parse(await result.file.text()), attachment=result.manifest.entries.find(e=>e.kind==='persistent-file').path; delete pkg.payloads[attachment]; result.file.write(JSON.stringify(pkg)); await assert.rejects(()=>service.verifyBackup(result.file),/missing/);
 pkg.payloads[attachment]=format.bytesToBase64(Uint8Array.from([9,9,9])); result.file.write(JSON.stringify(pkg)); await assert.rejects(()=>service.verifyBackup(result.file),/integrity/);
 pkg.manifest.formatVersion=2; result.file.write(JSON.stringify(pkg)); await assert.rejects(()=>service.verifyBackup(result.file),/Unsupported/);
 dirs.delete('document:/vehicle-photos'); files.clear(); dirs.add('document:'); dirs.add('cache:'); const empty=await service.createBackup(db,{now:new Date('2026-09-22T00:00:00.000Z')}); assert.equal(empty.manifest.persistentFileCount,0);
 const bad={serializeAsync:async()=>{throw Error('fail')},getFirstAsync:db.getFirstAsync}; await assert.rejects(()=>service.createBackup(bad,{now:new Date('2026-09-23T00:00:00.000Z')}),/snapshot/); assert.deepEqual([...source],[...before]);
 console.log('PASS: manifest/version/schema, database and attachments, SHA-256, verification, missing/corrupt/unsupported/unsafe data, cleanup, empty files, and source preservation.');
}
main().catch(e=>{console.error(e);process.exitCode=1});
